#
# Symmetric Encryption for Ruby
#
---
# For the development and test environments the test symmetric encryption keys
# can be placed directly in the source code.
# And therefore no RSA private key is required
development:   &development_defaults
  key:         1234567890ABCDEF1234567890ABCDEF
  iv:          1234567890ABCDEF
  cipher_name: aes-128-cbc
  encoding:    :base64strict

test:
  <<: *development_defaults

release:
  # Since the key to encrypt and decrypt with must NOT be stored along with the
  # source code, we only hold a RSA key that is used to unlock the file
  # containing the actual symmetric encryption key
  private_rsa_key: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIEowIBAAKCAQEAtMlG39h+B3G4x4yLkaAInesjX9OwFdmyI/9ysu/RTWO7/Axd
    6fJlftQchbXGeC4uCURw0aXOlbPIJb4dVwY7Pyr3Wgi6QIxIKSoa5eI3G73Oy7+f
    fycbs6YIfSfTOsRaEeJlJxeFIT2QWp9sVTi0Q9AGyEu+dhR7efifG54Zba5a2U3P
    squntO+6XFilicLXJzcJFXM39qWyKWyQVCwYwdTww4aDjhn0/Qwju6iOuJvSBJez
    kH+3FamXn8IuY998E1Aq5fIAA98kk1MaO1aPD0YJlJyrFuz/Qrv6zx+iVyyKpNBN
    y2DoijeJ20M3YBFAatubs8URe/RrorQZF7NiqwIDAQABAoIBADyduCvZ1Pf+A2y1
    DR74v6rjamr4+XN6GKbFQdoJWu5N4Hv0UZDde3Z4/E9A0Zj+MuVck09X/tpm+1bc
    Vc4WAst9Ro5jmr+FybQzr+0gWkXs8GeUipABtuIXa4U7UzHDIEga1ruywSqSD9Ky
    3Yn9h0OtfniuHOBOodAVspN6ASCq4vEO+GlOF6IJWomD6ucZAnAonQHo/OeyrPYR
    G5ZHQxYbVfEtEAUH3NYYl9FnplbNZ+TeGSl3L1gjNQGBaqRtAcKVv+f+ax4WCVLt
    POrz1VCNyDZVIkGsA3gZTvZicoEbTeDNOMXnkgzy+k/+fVmVFcpOiyFRGR9O60fM
    xRInCNECgYEA3EGIyrsPnEIgGe5+v/xKAKoQXCjWkU7C1HT9RVk9vgHiq5QCresT
    yrLlUiLvQ0GstJfNl8ttj86qq1SXMN+WIpRdduVEV/Z5ddyg2SPLiYsxROIKDq0n
    GzNSrl1PI4bcm8Yakw2Yy/Puwl1dc27N2Re/z9emT8oZuA4AW2ssl68CgYEA0h/7
    5c/Cnni9ubMkDnq3YZPtLh491S2uYttwRol44cg8gRugzl21CQRxowrssrng8LVk
    qKX2BURPUaQ3dEevxn/Q3YzNZtoxbUZ5xrd9mPSbzskEupPfmd7wDhLHj55P5ffQ
    k4mD45arHW9lObl0P47kprKSt4f1vwlF0svpJ8UCgYAbRPncr8BFBmLXExIaTvAS
    mPuhjWTTZL72cu2QknX0emNH/vE9+ybeJ7wAqVaaKx1o1oqbypHsBhhXUgfOA0Ch
    U2EnAUeu5FMxZnl7qNTgWJ1m+91m58U5tub7s43CxkW1+5b6sepDBhZ/dfPGAOf3
    gts6rmZm5oy8nu8oYmKI/QKBgAPtdx7nkEK4DQvQjmb64jyfsDpBdHRsoyrT4Thg
    T3Mg9AiRxKK227BsdddPV/dLRCobqeMBHyUgDr9+605wHJgAQZ4yiJBYmb3qKFKP
    kXhvcg4ecckvBGny4dfRgAtuMR4iULLBSkbRxScKswCuN78MY7e99MIbd3t3p+d1
    ykjlAoGBAKR4zCxv18xoFFoVeVvMKADAfkDegfGKljVoKpJ+03MNYJgCX2ma5T+C
    w5DK79OJUBWXMG038Ia0pqlFO9ez9f1BnVnkk3WdpHkhKY21kLSTCV0rxXtMt/T5
    +AVcUoE7UC6XwOUlv41jpvNqRcCP88NKaYbvJLT4/jqW+JCeNrsM
    -----END RSA PRIVATE KEY-----


  # List Symmetric Key files in the order of current / latest first
  ciphers:
    -
      # Filename containing Symmetric Encryption Key encrypted using the
      # RSA public key derived from the private key above
      encrypted_key: "<%= ENV['RELEASE_KEY1'] %>"
      iv:            "uNy7cCUS1+tVUpXm5NmAkg=="
      cipher_name:   aes-256-cbc
      # Base64 encode encrypted data without newlines
      encoding:      :base64strict
      version:       1

production:
  # Since the key to encrypt and decrypt with must NOT be stored along with the
  # source code, we only hold a RSA key that is used to unlock the file
  # containing the actual symmetric encryption key
  private_rsa_key: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIEowIBAAKCAQEA2zhc5Yd9bmlwxrjfeiJSaAnz7YUbl1TnFiKgV7WJV4BSK0re
    zDRfm6MMGyUYdCws0ewtMqcjQZN3O731hb+QDbuxpf9BpQj8qn+xq/HgCgngOSHQ
    iw/UOor1xzvsQzcoeZflEkUaYMs8cger1Ieh7/32auHdsNCWpTnbi/ZLqJADDMg4
    patJUoVi4RY3rxFQl1nE54cpeLhM+dMFLGh4SylucMj7kBO7R3eDFhzVOdUtClyG
    qGTtXytXhF7jR9JZWi0W/2MUWH4ORAT+irwFY1fPC0jlYrG5QcpWAT8Cdb5vABKz
    ZPyJICOOkQzrB6T9Ofg8ufXrfHw+cB3SXWG2xQIDAQABAoIBAQCUvBQDQz8uF2oF
    2k79vaWtovsWLxZ+QYOcOBgUCj5J2O1nJCAv6mTn4uMG089YmtQ6BYTQ9idsiZH/
    Pa4EdelV9//bAWnXgFZ1k7fHUo9QIE06Vh/5Cd9TbQ6+g4CURis2/IDWOX5hJ+M1
    9tB1nSSZAPUcpWxVV+Ct76huuMeyb+m0+VOZokhYn3H+znII9mGc0cc7GbBVpiJ4
    xCSgmg8JHSTYFe+8UBEgbsnwVAKdJoORL/RNsOXbJUCBiJWtwNcCGtdagCzQI4nN
    AszgG1YaXB7OxrlJc7FX442G7+zBudnG9zEicvYL1Yql2L2pqWb0+GEbm3eED2Xx
    JBz+Od5hAoGBAO/1jv6GOd3bAPajRSoYz8WKv17i9V6vEKxGLMdoawRw64jefj4j
    yH3vvrVXmgOVuKathWg3iLewDJpBkxDyOeqymB/9rFvZ1C8/SJqNKVJ1GLkBfIJz
    XfXCY590Dg5p/Sukh1xde/RW4jrQRkXjFcK+2hyXUYi9t/ozQJrN+iXpAoGBAOnf
    5TT4YVQBmjphqMUYDYQ8tYzBAHl1JtLq9lutKfzV+X0C2WJ+91FxxMD3zXUVznxb
    rhnO6TB5MjxTm2mnCp/osUbdYEulDqXfrxj5E0mxrBVBgNmO230B2gBaHYM1umos
    s+lNYmAXJgjb/pGlagDyGkX+4sEWbyN4OkuNrxR9AoGANwYkCBFXa5wwmF3QGlse
    KborL+LzSQbz180vr3ouMBKEsBn08OLbsqUrIgI4euH2OaJImSFC5HwmJ6kpxBUH
    Wt4hLBTLVTSaB0uHpokAFLxtMt84YeF6hkRQ+9ts7bk4KK3NrExzhA/4SGxB8Pyl
    nMaO1UeNlsGKUoE2K0lYNyECgYB9/+4Qt7BX/fUFdw/h/69oivyUtHZ4+TDNeWD4
    yzZPzUf4ncxYUGcWLeD+xYKfjfwM66fEp8DiKKlz7udP6HrE5Cx+LU5v8qENpJFF
    Nwu5LEu1t/CfRWPi2ViF0AcOZaflA+h5zQMvGcmYBE4GUcPmdojJJSUtOdTumxtt
    EQw+UQKBgAbMQcDOeXxJtraxKceO8z/yyarx6QB4GQfQr0O7iYnlXqAa5WBEGsNm
    oZaAu6NizcmlOaEEhldaaq/8JR1CsvDRoSXwrIZvj3B4I0bPW16bW9Ji//EKMUVX
    GQHpyC5IiAQGLpZ7spSe9tS3JV6jN/gDgo3RuRylS99aY0txulrg
    -----END RSA PRIVATE KEY-----


  # List Symmetric Key files in the order of current / latest first
  ciphers:
    -
      # Filename containing Symmetric Encryption Key encrypted using the
      # RSA public key derived from the private key above
      encrypted_key: "<%= ENV['PRODUCTION_KEY1'] %>"
      iv:            "jQY3Y5zD+Ltwt1s88EgUEA=="
      cipher_name:   aes-256-cbc
      # Base64 encode encrypted data without newlines
      encoding:      :base64strict
      version:       1
